CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS clients (
    id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name    VARCHAR(60) NOT NULL,
    email   VARCHAR(255) UNIQUE NOT NULL
);